workflows:
  ios-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and get Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Generate Podfile if missing
        script: |
          if [ ! -f ios/Podfile ]; then
            flutter build ios --release --no-codesign || true
          fi

      - name: Set iOS minimum deployment target to 13.0
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' 's/platform :ios.*/platform :ios, '\''13.0'\''/' Podfile
          else
            echo "platform :ios, '13.0'" | cat - Podfile > temp && mv temp Podfile
          fi
          cd ..

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
