workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS deployment version to 13.0
        script: |
          cd ios
          if [ -f Podfile ]; then
            sed -i '' 's/^#\? *platform :ios.*/platform :ios, '\''13.0'\''/' Podfile
          else
            echo "platform :ios, '13.0'" > Podfile
          fi
          cd ..
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
