workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          cd ios
          sed -i '' 's/^#\? *platform :ios.*/platform :ios, '\''13.0'\''/' Podfile
          cd ..
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
